/* automatically generated by JSCoverage - do not edit */
try {
  if (typeof top === 'object' && top !== null && typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window

    if (! top.opener._$jscoverage) {
      top.opener._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null) {
    // this is a browser window

    try {
      if (typeof top.opener === 'object' && top.opener !== null && top.opener._$jscoverage) {
        top._$jscoverage = top.opener._$jscoverage;
      }
    }
    catch (e) {}

    if (! top._$jscoverage) {
      top._$jscoverage = {};
    }
  }
}
catch (e) {}

try {
  if (typeof top === 'object' && top !== null && top._$jscoverage) {
    _$jscoverage = top._$jscoverage;
  }
}
catch (e) {}
if (typeof _$jscoverage !== 'object') {
  _$jscoverage = {};
}
if (! _$jscoverage['cache/cache-service.js']) {
  _$jscoverage['cache/cache-service.js'] = [];
  _$jscoverage['cache/cache-service.js'][1] = 0;
  _$jscoverage['cache/cache-service.js'][3] = 0;
  _$jscoverage['cache/cache-service.js'][4] = 0;
  _$jscoverage['cache/cache-service.js'][5] = 0;
  _$jscoverage['cache/cache-service.js'][6] = 0;
  _$jscoverage['cache/cache-service.js'][7] = 0;
  _$jscoverage['cache/cache-service.js'][11] = 0;
  _$jscoverage['cache/cache-service.js'][12] = 0;
  _$jscoverage['cache/cache-service.js'][17] = 0;
}
_$jscoverage['cache/cache-service.js'].source = ["getCacheExpirations <span class=\"k\">=</span> <span class=\"k\">function</span><span class=\"k\">()</span> <span class=\"k\">{</span>","","  <span class=\"k\">if</span><span class=\"k\">(</span>window<span class=\"k\">.</span>XMLHttpRequest<span class=\"k\">)</span> <span class=\"k\">{</span>","    <span class=\"k\">var</span> request <span class=\"k\">=</span> <span class=\"k\">new</span> XMLHttpRequest<span class=\"k\">();</span>","    request<span class=\"k\">.</span>onreadystatechange <span class=\"k\">=</span> <span class=\"k\">function</span><span class=\"k\">()</span> <span class=\"k\">{</span>","      <span class=\"k\">if</span><span class=\"k\">(</span>request<span class=\"k\">.</span>readyState <span class=\"k\">==</span> <span class=\"s\">4</span> <span class=\"k\">&amp;&amp;</span> request<span class=\"k\">.</span>status <span class=\"k\">==</span> <span class=\"s\">200</span><span class=\"k\">)</span> <span class=\"k\">{</span>","        window<span class=\"k\">.</span>pentahoCacheExpirationServiceResults <span class=\"k\">=</span> request<span class=\"k\">.</span>responseText<span class=\"k\">;</span>","      <span class=\"k\">}</span>","    <span class=\"k\">}</span>","","    request<span class=\"k\">.</span>open<span class=\"k\">(</span><span class=\"s\">\"GET\"</span><span class=\"k\">,</span> CONTEXT_PATH <span class=\"k\">+</span> <span class=\"s\">\"CacheExpirationService\"</span><span class=\"k\">,</span> <span class=\"k\">true</span><span class=\"k\">);</span>","    request<span class=\"k\">.</span>send<span class=\"k\">();</span>","  <span class=\"k\">}</span>","","<span class=\"k\">}</span>","","getCacheExpirations<span class=\"k\">();</span>"];
_$jscoverage['cache/cache-service.js'][1]++;
getCacheExpirations = (function () {
  _$jscoverage['cache/cache-service.js'][3]++;
  if (window.XMLHttpRequest) {
    _$jscoverage['cache/cache-service.js'][4]++;
    var request = new XMLHttpRequest();
    _$jscoverage['cache/cache-service.js'][5]++;
    request.onreadystatechange = (function () {
  _$jscoverage['cache/cache-service.js'][6]++;
  if (((request.readyState == 4) && (request.status == 200))) {
    _$jscoverage['cache/cache-service.js'][7]++;
    window.pentahoCacheExpirationServiceResults = request.responseText;
  }
});
    _$jscoverage['cache/cache-service.js'][11]++;
    request.open("GET", (CONTEXT_PATH + "CacheExpirationService"), true);
    _$jscoverage['cache/cache-service.js'][12]++;
    request.send();
  }
});
_$jscoverage['cache/cache-service.js'][17]++;
getCacheExpirations();
